# Generated by Django 4.1.7 on 2023-03-10 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonplayer',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.season'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonplayer',
            unique_together={('player', 'season')},
        ),
    ]
