# Generated by Django 4.1.7 on 2023-03-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonplayer',
            name='points_against',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seasonplayer',
            name='points_for',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
