# Generated by Django 4.1.7 on 2023-03-23 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_seasonplayer_points_against_seasonplayer_points_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonplayer',
            name='points_against',
        ),
        migrations.RemoveField(
            model_name='seasonplayer',
            name='points_for',
        ),
    ]
