repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.37.0
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  # Ruff fix (certain things)
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.210
    id: ruff-fix
    hooks:
      - id: ruff
        # F401 Remove unused imports
        args: ["--select", "F401", "--fix"]

  # Ruff lint afterwards
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.210
    id: ruff-check
    hooks:
      - id: ruff

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      - id: shellcheck
  - repo: local
    hooks:
      - id: mypy
        args:
          - --show-error-codes
        name: mypy
        types: [python]
        entry: poetry run mypy
        verbose: true
        require_serial: true
        language: system
