version: "3.8"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ${PWD}:/app:cached
      - ${HOME}/.aws:/root/.aws
    ports:
      - 8000:8000
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
    env_file:
      - ./.env.dev
      - ./.env.docker
    depends_on:
      - db

  worker:
    build: .
    command: dramatiq --watch app django_dramatiq_pg.worker --processes 1 --threads 4
    volumes:
      - ${PWD}:/app:cached
      - ${HOME}/.aws:/root/.aws
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_DEFAULT_REGION
    env_file:
      - ./.env.dev
      - ./.env.docker
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - ${PWD}/var:/share
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5466:5432

volumes:
  pgdata:
