# Generated by Django 4.1.7 on 2023-03-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='loser_mmr_change',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_mmr_change',
            field=models.IntegerField(default=0),
        ),
    ]
